name: PyLODE to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  pylode-to-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build Pages
        uses: vliz-be-opsci/pylode-to-pages@v0.1.11
        with:
          baseuri: https://ontology.golemlab.eu/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
